### ISSUE TITLE
Make comprehensions into Transformers

### ISSUE THREAD

**Issue by pakoito** [pakoito/RxComprehensions#1]
Requested by /u/prom85 : https://www.reddit.com/r/androiddev/comments/54el2e/rxcomprehensions_reduce_boilerplate_in_rxjava_12/d81gp4b?context=3

> I'd suggest writing transformers instead of static functions so that I can chain your functions into an observable queue via compose and don't have to break the chain.

**Comment by MFlisar** [comment]
Here's an example of how this could be improved (to support simple functions as well instead of observables):

```
public static void test()
{
    Observable<Integer> obs = Observable.just(0);

    Observable<String> res1 = obs.compose(applyFM(
                    a -> new Long((long)a + 1),
                    (a, b) -> "Int: " + a+  ", Long: " + b));

    Observable<String> res2 = obs.compose(applyFMObs(
            a -> Observable.just(new Long((long)a + 1)),
            (a, b) -> Observable.just("Int: " + a+  ", Long: " + b)));
}

public static <A, B, R> Observable.Transformer<A, R> applyFM(final Func1<A, B> one,
                                                           final Func2<A, B, R> two)
{
    return observable -> observable
            .flatMap(a -> Observable.just(one.call(a))
                    .flatMap(b -> Observable.just(two.call(a, b))));
}

public static <A, B, R> Observable.Transformer<A, R> applyFMObs(final Func1<A, Observable<B>> one,
                                                             final Func2<A, B, Observable<R>> two)
{
    return observable -> observable
            .flatMap(a -> one.call(a)
                    .flatMap(b -> two.call(a, b)));
}
```

**Comment by pakoito** [comment]
I've released compose() comprehensions, I believe it covers this use case well.

**Comment by MFlisar** [comment]
I now checked that and I think you missunderstood and I was not clear enough. My intention was to avoid breaking the chain. My example was not perfect to show that either. I now tried it and saw, that with the help of `Double`, `Triple` and so on classes we can achieve that and we stay reactive all the way.

I've made a demo in this gist: https://gist.github.com/MFlisar/c42510cf28463e7322695cc733732cb5

What do you think about that? Here's the usage in the way I would like it: https://gist.github.com/MFlisar/c42510cf28463e7322695cc733732cb5#file-composecomprehensionstest-java-L155

If you want to try it, just use my multiples library for testing: https://github.com/MFlisar/Multiples (it offers classes for grouping of objects from 2 (`Pair`) to 10 (`Decouple`))...

**Comment by pakoito** [comment]
I'm not sure I understand what part of that gist is supposed to go into a library, is it the zipper helper?

**Comment by MFlisar** [comment]
The `doFlatMapX()` functions... so you would use it with any observable at any place and just compose via `c.compose(RxComprehensions.doFlatMapX(...)`. You don't break the chain this way because the transformer can be chained via compose in a native rx way.

**Comment by pakoito** [comment]
Could you please check if those flatmaps in compose are chained one after another, such as you can access their values like in

```
obs1.flatMap {
  res1 -> ob2.flatMap {
    res2 -> obs3.flatMap {
     res3 -> /* res1 and res2 should be available here */ 
   }
  }
}
```

**Comment by MFlisar** [comment]
They are. The demo shows that as the demo observables get passed in all outer level flatMap values. To achieve that I need to use `Pair`, `Triple` and so on in the functions to pass on all outer values to the inner flatMaps

**Comment by MFlisar** [comment]
You access the `res1` and `res2` via a Pair (`res1` is `res.first` and `res2` is `res.second`) and at the next level you access `res1`, `res2` and `res3` via a Triple (`res1` is `res.first`, `res2` is `res.second` and `res3` is `res.third`) and so on...

**Comment by MFlisar** [comment]
The demo shows that you pass in a value to the first level observable and that this is passed on to the second level observable. The both results are passed on to the third level observable. So the demo shows how and that you can access outer flatMap levels values.

**Comment by pakoito** [comment]
I see it now. The problem is that the end of your chain ends up being a Pentuple<A, B, C, D, E> so you need an extra compose just to exit it with a final result. Plus your functions inside doFlatMap2 will rarely be reusable because of the composed type, you'll have to deconstruct the tuple first to simulate function parameters and it won't look great. The idea also creates a lot of intermediate objects just to pass the parameters around. And the end result is way too verbose with multiple compose(toFlatMapN()). There are also problems with zipping two observables of different lifecycles...

It's an interesting solution to reify parameters as Tuples and use zip, and nice to be kept as an experiment. It doesn't add anything to the existing constructs, plus comes with some inherent problems.

**Comment by pakoito** [comment]
I'd also look into adding equals, hashCode and toString into your tuples lib to make them comparable.

**Comment by MFlisar** [comment]
I don't see the problem with the final result. Just use `result.fifth` or call `map(result -> result.fifth)` to get the final result.

I don't see what is not reusable in `doFlatMap2` now, its completely generic.

Third, you're right, extra object generation is the downside, that's true.

**Comment by pakoito** [comment]
Because of type hinting it'll end up looking like

```
        getObs1(startValue)
                .compose(RxComprehensions.<One, Two>doFlatMap1(res1 -> getObs2(res1)))
                .compose(RxComprehensions.<One, Two, Three>doFlatMap2(res2 -> getObs3(res2.first, res2.second)))
                .compose(RxComprehensions.<One, Two, Three, Four>doFlatMap3(res3 -> getObs3(res3.first, res3.second, res3.third)))
                .map(one, two, three, four -> four)
```

Do you see the amount of noise it has compared to

```
doFlatMap(
 () -> obs1,
 one -> obs2(one),
 one, two -> obs3(one, two),
 one, two, three -> obs4(one, two, three),
)

**Comment by pakoito** [comment]
doFlatMap2 is reusable, the function you're passing to it requires 1 argument of type Tuple. When using function references it's easier to reuse functions with multiple parameters rather than using tuples on every function. It also disallows partial application and currying.

**Comment by MFlisar** [comment]
Actually the types are defined implicitly anyways, no need to define them. Following works as well:

	getObs1(startValue)
		.compose(RxComprehensions.doFlatMap1(res1 -> getObs2(res1)))
		.compose(RxComprehensions.doFlatMap2(res2 -> getObs3(res2.first, res2.second)))
		.compose(RxComprehensions.doFlatMap3(res3 -> getObs3(res3.first, res3.second, res3.third)))
		.map(data -> data.four)

But still the code is longer, that's true. Following can be done as well with a small change, but still, Pair, Triple and so on objects will be created:

	getObs1(startValue)
		.compose(RxComprehensions.doFlatMap1(res1 -> getObs2(res1)))
		.compose(RxComprehensions.doFlatMap2((res1, res2) -> getObs3(res1, res2)))
		.compose(RxComprehensions.doFlatMap3((res1, res2, res3) -> getObs3(res1, res2, res3)))
		.map(data -> data.forth)

And I don't have functions that need to work with Tuples, Triples and similar, you just dissolve them and pass their values to the next observable.
Anyways, it was just an idea, I'm not totally convinced of it either yet, because of the extra object creations, otherwise I would prefer the composibility.

**Comment by MFlisar** [comment]
You've pointed out the downsides, this shows the upsides:

Following example:

    RxComprehensions.doFlatMap(
		() -> getObs1(startValue),
		res1 -> getObs2(res1)
			.filter(res -> res > 0),
		(res1, res2) -> getObs3(res1, res2)
			.filter(res3 -> res1 + res2 + res3 > 0)
			.doOnNext(res3 -> L.d("OnNext: %d | %d | %d", res1, res2, res3))
	)
		.subscribe(data -> L.d("Subscribe: %d", data));

Will turn into:

	getObs1(startValue)
		.compose(doFlatMap1(res1 -> getObs2(res1)))
		.filter(res -> res.second > 0)
		.compose(doFlatMap2((res1, res2) -> getObs3(res1, res2)))
		.filter(data -> data.first + data.second + data.third > 0)
		.doOnNext(data -> L.d("OnNext: %d | %d | %d", data.first, data.second, data.third))
		.map(data -> data.third)
		.subscribe(data -> L.d("Subscribe: %d", data));

You get:
* 1 level of intention
* access to each result of each level at top level, which makes using them in rxjava functions possible without nesting

Still, the extra object creations are a downside. Not sure if it's worth adding this, but it has it's upsides as well...

**Comment by pakoito** [comment]
Those examples are not equivalent.

```
obs.flatMap(origin -> obs1.toList())
```
is not the same as 

```
obs.flatMap(origin -> obs1)
      .toList()
```

and that's one of the reasons why I wanted to create this library to highlight these kind of misunderstandings. Sure, filter and map work well at any point of the chain, but not operators like subscribeOn, takeUntil, reduce, and toXXX where the upstream source matters.

**Comment by MFlisar** [comment]
That was a mistake, I think now it's the same...
