### ISSUE TITLE
Why would you nest the flatmap calls at all?

### ISSUE THREAD

**Issue by grandstaish** [pakoito/RxComprehensions#2]
I've seen this library pop up a few times and every time I see it I wonder why I would ever write code like you have in the sample. My understanding is that the example in the readme could be re-written without nesting like so:

```
Observable<String> getUserFriends = profileClicks()
    .flatMap { position -> getUserFromProfile(position) }
    .flatMap { user -> requestFriendListForUser(position, user.id) }
    .flatMap { friends -> storeUserAndFriends(user, friends) }
    .flatMap { result -> toUserDisplayString(position, user, friends, result) }
    .subscribe(...)
```

This is much clearer to me and doesn't require an additional library. In what situation would nesting flatmap calls be beneficial?

**Comment by pakoito** [comment]
Try this:

```
PublishSubject<Integer> origin = PublishSubject.create();

origin
  .flatMap(num -> Observable.range(0, num))
  .toList()
  .subscribe(num -> println(num))

origin.onNext(1);
origin.onNext(2);
origin.onNext(3);
origin.onNext(4);
```

And see how many numbers are printed, then try to fix it :D 

That's the first problem about understanding mismatched Observable lifecycles, and how bringing them to top level can help with readability and reasonability.

**Comment by pakoito** [comment]
The second problem:

```
Observable<String> getUserFriends = profileClicks()
    .flatMap { position -> getUserFromProfile(position) }
    .flatMap { user -> requestFriendListForUser(position, user.id) }
    .flatMap { friends -> storeUserAndFriends(user, friends) }
    .flatMap { result -> toUserDisplayString(position, user, friends, result) }
    .subscribe(...)
```

This chain isn't possible because you don't have access to the lambda of the previous flatMap. requestFriendListForUser won't have access to position, and toUserDisplayString doesn't have access to position, user, friends.

Check it on a project. You have to nest them.

**Comment by grandstaish** [comment]
Ah yeah I see it now, I somehow missed the fact that you're passing all of the results from the previous observables down the chain. My bad!
